### ISSUE TITLE
Extensible Data Notation (.edn) syntax support?

### ISSUE THREAD

**Issue by xpe** [MattDMo/Neon-color-scheme#11]
The [EDN format](https://github.com/edn-format/edn) is a subset of Clojure's syntax (though not coupled to Clojure in particular). So I'm surprised that they don't look nicer when highlighted as Clojure.

Currently, my EDN files only have white and gray. I would like if it looked more look more like JSON, which has amazing rainbow coloring as you descend deeper!

![rainbow-highlighting](https://f.cloud.github.com/assets/4576329/1751285/3a65f4c8-65da-11e3-9418-f83330e45f0f.png)

I would think that, at least, strings and keywords would be distinctly colored. But now that I look at Clojure highlighting, I'm seeing the problem

What would be a decent way to improve EDN highlighting? (I'm not sure if this is in-scope for this code base.)

**Comment by leesei** [comment]
Sublime Text accept issues [here](https://github.com/SublimeTextIssues).
You see, Neon is only a color scheme (a great one I may add). You need a good syntax definition together with it.
