### ISSUE TITLE
Change TODO comment line highlighting

### ISSUE THREAD

**Issue by ChrisCalderon** [MattDMo/Neon-color-scheme#14]
Currently, it only highlights a TODO if there is one `#` at the front of the comment, but I like to use different levels, like `#`, `##`, and `###` for comments, and `### TODO` doesn't get the pretty highlighting. I have no idea how syntax highlighting works, and I would change this myself and not bother you if I knew how. This is the one thing I wand to change about your amazing color scheme.

**Comment by MattDMo** [comment]
Moved to [PythonImproved issue 35](https://github.com/MattDMo/PythonImproved/issues/35)
