### ISSUE TITLE
Better jsx support?

### ISSUE THREAD

**Issue by rubyruy** [MattDMo/Neon-color-scheme#17]
As in react.js. 

I'm honestly not sure if the highlighting is off because of the theme or just because the syntax scopes are wrong are totally off in the ReactJS package. But hey, the little update window told me to open a ticket, so here I am :)

**Comment by MattDMo** [comment]
Thanks for the feedback. Since I'm not familiar with ReactJS, could you post some code, along with a screenshot of what you're seeing, and what you think should be different? The built-in JavaScript syntax definition is pretty lousy, so that may be part of the problem.

**Comment by rubyruy** [comment]
Certainly:

(snippet from http://facebook.github.io/react/#todoExample)
![jsx-neon](http://i.imgur.com/cm8Y46K.png)


On the left is some JSX code which includes embedded HTML, on the right is how the color theming for that HTML should  probably look.

**Comment by leesei** [comment]
[Babel](https://packagecontrol.io/packages/Babel) provides syntax files an two color schemes.
It does define some extra scopes for the embedded JSX. I think Neon can pick them up.

**Comment by MattDMo** [comment]
Yeah, can you tell Neon hasn't had the highest priority in my life lately? Sorry about that. At any rate, with the help of the new `JavaScript.sublime-syntax` in the most recent dev builds, as well using Babel, I've added and tweaked a bunch of scopes that should make your JSX look much nicer. They were added in 278c3a1, and I'll be pushing out a new release in the next day or so, hopefully. Thanks!
