### ISSUE TITLE
Question about different colors - modification

### ISSUE THREAD

**Issue by cornz** [MattDMo/Neon-color-scheme#21]
I have two questions on how to modify your great theme to my needs.

I just started using sublime with your theme and while it's really great I want to add something in the coloring for editing JSON:
1) How do I change the bracket highlighting? I simply can't get used to underlining, I need a color change :)
2) I'm using a custom format with a custom programming language and have to use bracket containers such as seen in this picture: ![custom](http://i.imgur.com/nuOdx7W.jpg) - any chance to change the contents of the [ ] brackets to a different color than the other text?

Thanks for your theme!!

**Comment by MattDMo** [comment]
Hi Cornelius,
Sorry for the delay in getting back to you, my real job has been really busy and I haven't had any time to focus on side projects like this for a little while. Anyways, to answer your questions:

**1)** Check out [`BracketHighlighter`](https://packagecontrol.io/packages/BracketHighlighter) on Package Control. Color schemes like Neon don't affect how brackets/braces/parens/etc. are highlighted, unless they're part of the language syntax definition, which in the case of JSON they are not. `BracketHighlighter` allows you to customize all that, and much more. Also, you can disable underlining of matching brackets by setting
```js
"match_brackets": false
```
in **`Preferences -> Settings-User`**.

**2)** This type of highlighting has to be defined by the language's syntax definition, which creates a scope. A color scheme like Neon then assigns a color to a scope. So, what you would need to do for your custom language is modify the `JSON.tmLanguage` file (using [`AAAPackageDev`](https://packagecontrol.io/packages/AAAPackageDev) makes that a lot easier) and alter the `string` definition to scope opening and closing square brackets. You can then modify `Neon.tmTheme` and add a color and other styling to those brackets.

**Comment by cornz** [comment]
Thanks for your answers - I figured it out after some researching and modified the theme to my liking!
