### ISSUE TITLE
support for the Rust programming language

### ISSUE THREAD

**Issue by freinn** [MattDMo/Neon-color-scheme#22]
Hi!

Rust is a very nice language and I want your color scheme to support it. Thanks in advance.

**Comment by MattDMo** [comment]
Sure, I'll see what I can do. In the meantime, if you could add some links to some Rust resources, as well as an example file or two that contains as many of the language's features as possible so I can test the highlighting.

Thanks.

**Comment by freinn** [comment]
Okay, I'm a Rust newbie (I've wrote a hello world half hour ago xD), but I will try to help you as much as I can. Thanks!

**Comment by freinn** [comment]
I've created [this thead](https://users.rust-lang.org/t/help-for-creating-a-syntax-highlighting-color-scheme-for-sublime-text/2900) to get help.

**Comment by MattDMo** [comment]
I forgot to mention this issue in the commit message, but I just pushed 278c3a1, which has a bunch of Rust-specific stuff in it. I'll be releasing a new version of Neon to Package Control in the next day or so, please let me know how it looks. They syntax is kind of bare, but I did what I could.
