### ISSUE TITLE
highlighting TODO, FIXME etc

### ISSUE THREAD

**Issue by xtotdam** [MattDMo/Neon-color-scheme#24]
Hi!
Thank you for your great Sublime extensions!
As soon as we use comments like `# TODO something` not only in Python, but also in many other languages, perhaps it would be wise to generalise its color definition for every language since `comment.line.note.python` and `comment.line.note.notation.python` are too strict? I have tried to fix it myself, but failed =(

**Comment by MattDMo** [comment]
The reason they are the way they are is because those scopes are specific to [Python Improved](https://packagecontrol.io/packages/Python%20Improved). If you find they exist in other language definitions I can certainly alter Neon, so just let me know if you see them.

**Comment by xtotdam** [comment]
C and Python often are used in the same project, so I am trying to make Neon and [CImproved](https://github.com/abusalimov/SublimeCImproved) friends. As you can see, its creator is now altering it to support such highlighting ([there](https://github.com/abusalimov/SublimeCImproved/issues/27)) and is very optimistic. I am really looking forward that such highlighting appears for C too.

**Comment by MattDMo** [comment]
Ah, I didn't know about that. I'll add this modification to the next release.

**Comment by xtotdam** [comment]
Thank you in advance

**Comment by xtotdam** [comment]
Thank you!
