### ISSUE TITLE
What about assembler?

### ISSUE THREAD

**Issue by ktwzk** [MattDMo/Neon-color-scheme#25]
Hey, I think, that syntax highlighting of MASM/NASM will be really useful :smiley:

**Comment by MattDMo** [comment]
Thanks for the feedback, and I apologize for taking so long to get back to you. Unfortunately, there are quite a few language definitions for various versions of assembly, and there is very little overlap amongst them as far as scopes are concerned, so it would be rather difficult to create a unified experience. I installed a few, and for the most part they look pretty decent with Neon already, so I'm not sure what else I could do that wouldn't involve installing [all of the `assembly` packages](https://packagecontrol.io/search/assembly) and trying to customize each one. 

If you use one particular syntax highlighting definition and would like me to add a few scopes, please give me a link to the package you're using, as well as some *detailed* sample code with hints as to what in particular you'd like highlighted that currently isn't (images would also help), and I'll consider it further.
