### ISSUE TITLE
New SublimeText 3 beta update breaks highlighting

### ISSUE THREAD

**Issue by kgizdov** [MattDMo/Neon-color-scheme#27]
Since SublimeText 3 Build 3103 the bracket highlighting for functions doesn't work for me. The first bracket in a couple is highlighted correctly, but the second one is not. I'm guessing this is because the new syntax highlighting changes in SublimeText.

**Comment by MattDMo** [comment]
I'm afraid I'm not sure what you're talking about, or how it's related to Neon. Could you please post some images demonstrating the problem you're having?

**Comment by kgizdov** [comment]
OK, here's some screenshots
![monokai](https://i.imgur.com/y7MUs1N.png)
![Neon](https://i.imgur.com/Dy46DJ5.png)

The first screenshot shows that Monokai does not highlight brackets and I only get bracket highlighting with Neon. I've tried disabling other packages to make sure it's not something else, but I couldn't find anything else.

So before the big update, Neon used to highlight both brackets. And I was just guessing that the new highlighting macros from Sublime have something to do about it. I hope this makes more sense.

**Comment by MattDMo** [comment]
OK, thanks, I'll take a look at it.

**Comment by kgizdov** [comment]
Oh, it seems there's even more stuff to look at. If you go over the commits on [this page](https://github.com/sublimehq/Packages/commits/master/C%2B%2B/C%2B%2B.sublime-syntax), you'll notice the syntax highlighting for C++ has changed a lot. Adding brackets, constants, etc to the mix of new stuff.

**Comment by MattDMo** [comment]
Yes, there have been many changes to a bunch of syntaxes - I've been following the sublimehq/Packages repo, so I get all the updates. I'm currently working on the JavaScript syntax, but I'll try to cover C++ and all the rest as well.

**Comment by MattDMo** [comment]
So it looks like the C++ definition got fixed. Here is the same code as above using a version of Neon that I'm hoping to release quite soon.
![neon issue 27](https://cloud.githubusercontent.com/assets/1776358/16533059/1d9aff36-3fa4-11e6-8cfc-d1c84e645873.png)

**Comment by kgizdov** [comment]
looks really nice. I was wondering if bracket highlighting is on the table - it looked really good before
