### ISSUE TITLE
For other editor

### ISSUE THREAD

**Issue by Alexey-T** [MattDMo/Neon-color-scheme#28]
Hi. 
Maybe possible to 'port' theme to Cudatext [uvviewsoft.com] ?

**Comment by MattDMo** [comment]
Hi Alexey,
I'm not familiar with that software, and couldn't find any information on the format of the color scheme. If you use the same `tmTheme` format as Sublime/TextMate, you can just download the appropriate file from the repo and use it. However, if you use a different format, it will all have to be done manually, and I honestly don't have time for that.

**Comment by Alexey-T** [comment]
Format is Json file, saved in folder data/themes. App has visual dialog to config theme.
