### ISSUE TITLE
Horizontal Lines Between Selected Lines

### ISSUE THREAD

**Issue by ghost** [MattDMo/Neon-color-scheme#31]
Is there any way to get the syntax selection to work like it does on your Sublime version of this theme? By this I mean is there a way to set the green stroke to wrap around just the outside of the selection. I love how it wraps like a glowing bubble on Sublime. 

Sublime
<img width="339" alt="sublime-neon-syntax" src="https://cloud.githubusercontent.com/assets/20247961/21408975/dbe8f068-c7a5-11e6-99c7-0d864ec1dabe.png">

Atom
<img width="435" alt="atom-neon-syntax" src="https://cloud.githubusercontent.com/assets/20247961/21408993/ef6dfd54-c7a5-11e6-9be9-5bcc6342851c.png">

**Comment by MattDMo** [comment]
This appears to be an issue with how Atom does selections and assigns borders to them, and not anything intrinsic to Neon itself. So, unfortunately, there's nothing I can do on this end to fix it.
