### ISSUE TITLE
ClojureScript - numeric keys wrong coloring

### ISSUE THREAD

**Issue by ItamarShDev** [MattDMo/Neon-color-scheme#32]
as you can see the the image below, every key that starts with a number has the pink background.
This is very confusing and eye-catching, yet the keys are correct and has no reason to be marked.

is it fixable? 
if it a small fix i can do myself locally, i'll be happy to do it by your guidance.
 
![image](https://cloud.githubusercontent.com/assets/953371/21846238/ea44f5ee-d7fe-11e6-8f1b-30453dbd26cc.png)

 thanks!

**Comment by MattDMo** [comment]
What version of Sublime are you using, and which ClojureScript syntax?

**Comment by ItamarShDev** [comment]
any update?

**Comment by MattDMo** [comment]
Sorry, I was out of the development game for several years and am just now getting back into things and going through old issues. I can't reproduce this, either with the current build (3.2.2) of Sublime Text 3 or with an alpha build of ST4.
