### ISSUE TITLE
Flex and Bison syntaxic color.

### ISSUE THREAD

**Issue by zaurelzo** [MattDMo/Neon-color-scheme#33]
Hey, thanks for your awesome theme.
I was wondering if you 've planned to customize it for flex and bison files ? I tried to customize your theme for these specific files but I could not make it.

**Comment by MattDMo** [comment]
@zaurelzo sorry it's been a few years. I could only find a Sublime syntax definition for Bison, but I added a few scopes to Neon so it looks a little better than default. Please let me know if you have any feedback
