### ISSUE TITLE
Light Theme

### ISSUE THREAD

**Issue by vijer** [MattDMo/Neon-color-scheme#34]
Hey Matt,

Overall I like the color scheme, but I don't really like black backgrounds, have you tried making this with a white background?

Vince

**Comment by MattDMo** [comment]
Hi Vince,
I have, but it really doesn't look that great, at least to me. The white background mutes a lot of the bright colors, making them harder to see. Some worked okay, but I'd basically have to redesign 90% of the thing. I prefer dark/black backgrounds anyway, so spending time making something I wouldn't really like to use didn't seem like a good use of my time. However, you (or anyone else) are welcome to attempt a white Neon - just drop me a line and I'll link to it.

Matt
