### ISSUE TITLE
Make YAML like JSON?

### ISSUE THREAD

**Issue by bikeboy99** [MattDMo/Neon-color-scheme#37]
This theme is awesome, it is one of the few themes I've found that highlights JSON in a sensible way.  I noticed that the YAML "levels" are not highlighted like JSON - any plan to add that?  I don't have experience developing themes but I could try adding it myself, if you think it's an OK idea.

Thanks!

**Comment by MattDMo** [comment]
Sorry I missed your issue for so long, I've been out of the development game for several years and I'm just now starting up again. If you're still interested in this, please attach 1 or more example files and I'll see what I can do.

**Comment by MattDMo** [comment]
So I've looked into this, and unfortunately the YAML language definition doesn't nest levels hierarchically like the JSON one does, so there's no way for the color scheme to tell which level is which.
