### ISSUE TITLE
JSON colors the same regardless of level

### ISSUE THREAD

**Issue by davaya** [MattDMo/Neon-color-scheme#39]
The package seemed to install correctly in Sublime 3 v3,2,2,, opening a Package Control Message for Neon Color Scheme v2.0.0.

The JSON file parses correctly, with JSON shown in the lower right, and the appropriate scopes as shown in the screenshot.

But all strings are the same gold color, regardless of nesting level, object or array.   Is there any additional configuration required?

(Note: Neon works great with Python, with bright blue entity.name.function.python and green variable.function.python, etc.)

![sublime-neon](https://user-images.githubusercontent.com/19152940/69466310-b3e71780-0d51-11ea-9cc0-bb22fe7e38a4.jpg)

**Comment by MattDMo** [comment]
If this is still relevant, could you attach a test file where I can check the behavior?

**Comment by vladdancer** [comment]
Hi Matt.

Thanks for this great theme!
I'm experience the same issue with JSON highligting on any json. I'm using Sublime 3.2.2 + with fresh installed Neon Color Scheme. 
I believe this issues are related too:
https://github.com/ColibriApps/MonokaiJsonPlus/issues/7
https://forum.sublimetext.com/t/rainbow-colors-by-json-object-level-with-any-color-scheme/42968/2

**Comment by MattDMo** [comment]
@vladdancer It looks like the JSON syntax was changed some time ago, breaking Neon's functionality. I'm trying to fix it now...
