### ISSUE TITLE
where is this pink coming from?

### ISSUE THREAD

**Issue by rowe-morehouse** [MattDMo/Neon-color-scheme#43]
I am trying to use neon for markdown … it all looks good to me, but where is the pink #fc00ed coming from?

This is a screenshot from your readme:

<img width="448" alt="20201002-Fri-03-06-05@2x" src="https://user-images.githubusercontent.com/2647082/94912358-66046b00-045c-11eb-9cb3-45081c1ac551.png">

I want to turn OFF the pink background on the asterisk. 

I want markdown `*` and `-` to be white, like the text. 

Tried for a long time to figure it out — can you let me know? Thanks in advance. :)

**Comment by MattDMo** [comment]
Thanks for the comment. Go to your `Packages` folder, then `Neon Color Scheme`, then open `Neon.sublime-color-scheme` in Sublime with JSON syntax (or Sublime Text Color Scheme (JSON) if you have [`PackageDev`](https://packagecontrol.io/packages/PackageDev) installed). This rule is defined on lines 1461-1466. Just comment them out with `//` at the beginning of each line, save the file, and you should be all set.
```js
// {
//     "name": "List",
//     "scope": "markup.list punctuation.definition.list_item",
//     "foreground": "#000000",
//     "background": "#F90BEA"
// },
```

Keep in mind that you'll have to redo this every time Neon is updated. I just did a major update to version 3.0, and I've been pushing out point updates as issues come in, so just keep an eye on your Package Control messages.
