### ISSUE TITLE
No screenshots

### ISSUE THREAD

**Issue by skylogic004** [MattDMo/Neon-color-scheme#44]
You need screenshots! No one wants to download something before they know what they're getting!

In particular, I'm referring to this page: https://packagecontrol.io/packages/Neon%20Color%20Scheme

But the readme of the git repo should have them too.

**Comment by MattDMo** [comment]
Sorry about that. The company that I was hosting with went out of business, and I forgot to grab the screenshots before my server went down for good. I'll make some new ones this weekend.
