### ISSUE TITLE
question

### ISSUE THREAD

**Issue by rowe-morehouse** [MattDMo/Neon-color-scheme#45]
Thanks for the cool color theme, love me some neon. :)

What is the cool ascii font you are using, and where can I make it?

<img width="765" alt="20210418-Sun-01-01-22@2x" src="https://user-images.githubusercontent.com/2647082/115138605-0b8ac080-9fe2-11eb-8aea-d8b9282ba017.png">

**Comment by MattDMo** [comment]
The site is http://patorjk.com/software/taag/#p=display&h=0&v=0&f=Georgi16&t=Type%20Something. I used the Georgi16 font, and when you hit the <kbd>More Opts</kbd> button, I chose the C++ style `//` comments in the formatting dropdown. It's a pretty cool site, I think they have over 300 fonts/styles available now.
