### ISSUE TITLE
 Neon-color-scheme for VS code

### ISSUE THREAD

**Issue by arabnejad** [MattDMo/Neon-color-scheme#47]
Hi @MattDMo 

how we can have your theme scheme for VS code ? is there any way?
I really like the colour scheme of this theme for python code, and was wondering if we can have it for VS code

Regards,
Hamid

**Comment by arabnejad** [comment]
sorry, my bad
This is already asked #40

**Comment by MattDMo** [comment]
@arabnejad Thanks for finding the dupe, I was about to search for it myself. I've done a bunch of googling, and it seems that no one has written a `.sublime-color-scheme` JSON to VSCode JSON converter, and I just don't have the time or the interest. Maybe someday when work isn't quite so crazy.
